version: "3.3"
services:
  database:
    image: postgres # use latest official postgres version
    container_name: postgres
    ports:
      - 5432:5432
      - 5000:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=programs
    volumes:
      - db:/var/lib/postgresql/data/ # persist data even if container shuts down
  backend:
    build: .
    container_name: test-be
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - DJANGO_DEVELOPMENT_DATABASE=database
      - DJANGO_ENVIRONMENT=development
volumes:
  db: ~
